services:

  backend:
    build:
      context: ./namistore-backend
      dockerfile: Dockerfile

    container_name: namistore-backend-container

    ports:
      - "5000:5000"

    env_file:
      - ./namistore-backend/.env.local

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./namistore-backend/uploads:/app/uploads


  frontend:
    build:
      context: ./namistore-frontend
      dockerfile: Dockerfile

      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000

    container_name: namistore-frontend-container

    ports:
      - "3000:3000"

    depends_on:
      - backend