apiVersion: apps/v1
kind: Deployment
metadata:
  name: namistore-backend
  namespace: namistore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namistore-backend
  template:
    metadata:
      labels:
        app: namistore-backend
    spec:
      containers:
        - name: namistore-backend
          image: 274703560582.dkr.ecr.ap-south-1.amazonaws.com/namistore-backend:17
          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: namistore-backend-config
                  key: PORT

            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: namistore-backend-config
                  key: AWS_REGION

            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: namistore-backend-config
                  key: AWS_S3_BUCKET_NAME

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: namistore-backend-secrets
                  key: DATABASE_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: namistore-backend-secrets
                  key: JWT_SECRET

            - name: RAZORPAY_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: namistore-backend-secrets
                  key: RAZORPAY_KEY_ID

            - name: RAZORPAY_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: namistore-backend-secrets
                  key: RAZORPAY_KEY_SECRET

          
